class Room {
  List<Rooms>? rooms;
  Room({data});
  Room.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      rooms = <Rooms>[];
      json['data'].forEach((v) {
        rooms!.add(Rooms.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (rooms != null) {
      data['data'] = rooms!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Rooms {
  String? sId;
  String? messageId;
  String? chatRoomId;
  Message? message;
  String? type;
  PostedByUser? postedByUser;
  List<ReadByRecipients>? readByRecipients;
  List<People>? roomInfo;
  String? createdAt;

  Rooms(
      {sId,
        messageId,
        chatRoomId,
        message,
        type,
        postedByUser,
        readByRecipients,
        roomInfo,
        createdAt});

  Rooms.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    messageId = json['messageId'];
    chatRoomId = json['chatRoomId'];
    message =
    json['message'] != null ? (json['message'] is String ? Message(messageText: json['message']) : Message.fromJson(json['message'])) : null;
    type = json['type'];
    // postedByUser = json['postedByUser'] != null
    //     ? PostedByUser.fromJson(json['postedByUser'])
    //     : null;
    if (json['readByRecipients'] != null) {
      readByRecipients = <ReadByRecipients>[];
      json['readByRecipients'].forEach((v) {
        readByRecipients!.add(ReadByRecipients.fromJson(v));
      });
    }
    if (json['roomInfo'] != null) {
      roomInfo = <People>[];
      json['roomInfo'].forEach((v) {
        if(v!=null) {
          roomInfo!.add(People.fromJson(v));
        }
      });
    }
    createdAt = json['createdAt'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['_id'] = sId;
    data['messageId'] = messageId;
    data['chatRoomId'] = chatRoomId;
    if (message != null) {
      data['message'] = message!.toJson();
    }
    data['type'] = type;
    if (postedByUser != null) {
      data['postedByUser'] = postedByUser!.toJson();
    }
    if (readByRecipients != null) {
      data['readByRecipients'] =
          readByRecipients!.map((v) => v.toJson()).toList();
    }
    if (roomInfo != null) {
      data['roomInfo'] = roomInfo!.map((v) => v.toJson()).toList();
    }
    data['createdAt'] = createdAt;
    return data;
  }
}

class Message {
  String? messageText;

  Message({messageText});

  Message.fromJson(Map<String, dynamic> json) {
    messageText = json['messageText'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['messageText'] = messageText;
    return data;
  }
}

class PostedByUser {
  String? sId;
  String? firstName;
  String? lastName;
  String? type;
  String? createdAt;
  String? updatedAt;
  int? iV;

  PostedByUser(
      {sId,
        firstName,
        lastName,
        type,
        createdAt,
        updatedAt,
        iV});

  PostedByUser.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    firstName = json['firstName'];
    lastName = json['lastName'];
    type = json['type'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['_id'] = sId;
    data['firstName'] = firstName;
    data['lastName'] = lastName;
    data['type'] = type;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = iV;
    return data;
  }
}

class ReadByRecipients {
  String? readByUserId;
  String? readAt;
  List<People>? readByUser;

  ReadByRecipients({readByUserId, readAt, readByUser});

  ReadByRecipients.fromJson(Map<String, dynamic> json) {
    readByUserId = json['readByUserId'];
    readAt = json['readAt'];
    if (json['readByUser'] != null) {
      readByUser = <People>[];
      json['readByUser'].forEach((v) {
        readByUser!.add(People.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['readByUserId'] = readByUserId;
    data['readAt'] = readAt;
    if (readByUser != null) {
      data['readByUser'] = readByUser!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Autogenerated {
  String? sId;
  String? firstName;
  String? lastName;
  String? type;
  String? createdAt;
  String? updatedAt;
  int? iV;

  Autogenerated(
      {sId,
        firstName,
        lastName,
        type,
        createdAt,
        updatedAt,
        iV});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    firstName = json['firstName'];
    lastName = json['lastName'];
    type = json['type'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['_id'] = sId;
    data['firstName'] = firstName;
    data['lastName'] = lastName;
    data['type'] = type;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = iV;
    return data;
  }
}
class People {
  String? sId;
  String? firstName;
  String? lastName;
  String? type;
  String? createdAt;
  String? updatedAt;
  int? iV;

  People(
      {sId,
        firstName,
        lastName,
        type,
        createdAt,
        updatedAt,
        iV});

  People.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    firstName = json['firstName'];
    lastName = json['lastName'];
    type = json['type'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['_id'] = sId;
    data['firstName'] = firstName;
    data['lastName'] = lastName;
    data['type'] = type;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = iV;
    return data;
  }
  String getAvatarName() {
    String avatarName = '';
    if(firstName != '' && firstName != null) {
      avatarName += firstName![0];
    }
    // if(lastName != '' && lastName != null) {
    //   avatarName += lastName![0];
    // }
    return avatarName;
  }
}

